services:
  userbot:
    build: .
    image: kitoblar_bot:alpine
    container_name: exam-bot-con
    restart: always
    command: "python3 main.py"
    depends_on:
      - db
  db:
    image: kitoblar_menu:alpine
    container_name: pg
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql

volumes:
  pg_data: